### ISSUE TITLE
possible new johnoliver sub: r/AccidentalRenaissance

### ISSUE THREAD

**Issue by robertafreese** [username-is-required/reddark-subinfo#202]
[Poll results](https://old.reddit.com/r/AccidentalRenaissance/comments/14ex83g/ar_poll_results_are_in/) posted yesterday, today has seen some really nice artwork posted.

**Comment by username-is-required** [comment]
**thanks so much** <sub>/gen</sub> for flagging this sub! the artwork there is really something (in a good way), and i’m glad it’s going on the list.

annoyingly my bot didn’t pick up on it (because the post announcing the results wasn’t stickied), so thanks again for manually flagging. i’ll add a label to this issue to hopefully remind me to check in on it every so often (to make sure it’s still sticking to the john oliver theme).

anyway. **CONFIRMED JOHNOLIVERIFIED**

<hr>

relevant part of the post for posterity:

> You voted, we listened. We are now accepting photos of John Oliver, and **the names "John" or "Oliver" must be somewhere in the title.**
> 
> The photos can be as Renaissance as you like, from photoshops like the banner image, or AI, or just slap an oil paint filter on it. Or don't. Honestly, as long as John Oliver is in it? And it isn't NSFW? You're golden.
> 
> **If you came to the comment section to ask why the hell we're accepting photos of John Oliver:**
> 
> We took a vote and "Reopen the sub and only accept photos of John Oliver" was [overwhelmingly the top choice.](https://i.imgur.com/4Uj9TgW.jpg) We on the mod team might be ["landed gentry,"](https://gizmodo.com/reddit-ceo-steve-huffman-moderators-landed-gentry-1850546737) but we believe in democracy.
